### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by AbeeraTahir** [AbeeraTahir/To-Do-list#3]
This issue is opened for the peer-to-peer code review by the morning session team.

**Comment by SimonGideon** [comment]
## @AbeeraTahir Your code is clean :small_airplane: 
You kept much effort to have such an ordeal code, I made few observations, It will be better if you split your js file into modules for easy management of code functionality:slightly_smiling_face: :+1: kudoz :trophy: happy codding :100:

**Comment by enoqueJonas** [comment]
## Good job
Great job with the project.
### Highlights
- The code is well organized 
- The README file looks professional

There is nothing I could improve.
